export default {
  label: 'Fill Ups',
  id: 'fill-ups',
  list: [
    {
      id: 'fillup-1',
      label: 'Fillup - Collection 1',
      type: 'fillupOptions',
      commonData: {
        title: 'Click on the blanks and pick the correct option.'
      },
      data: [
        `Two men *were(was,is)* walking along one summer day. Soon *it(they,is)* became too hot to go any further. seeing *a(an,the)* large plane tree nearby, they threw themselves on the ground to rest in its shade. Gazing up into *the(a,an)* branches one man said to the other that the tree *is(are,were)* useless. It does not *have(has,has)* fruit or nuts that we can eat. we cannot even use *its(their,them)* wood for anything. Suddenly *the(a,an)* tree replayed him *(his,her)* not to be so ungrateful. It also said at *this(that,these)* very moment the tree *is(was,it)* very useful for them because it is shielding them from the hot sun. but he called *the(a,an)* tree good-for-nothing. The man who commented on the tree realised *his(him,her)* mistake and apologised to the tree.`,

        `Once upon a time, there *was(is,are)* a king who ruled a prosperous country. One day, he went for *a(an,the)* trip to some distant areas of *his(her,their)* country. When he *was(is,are)* back to his palace, he complained that *his(their,they)* feet were very painful, because it was *the(a,an)* first time that he went for such a long trip, and the road that *he(she,it)* went through was very rough and stony. *He(his,she)* then ordered his people to cover every road of *the(a,an)* entire country with leather. Definitely, this would need thousands of cows’ skin, and would cost a huge amount of money. Then one of *his(her,him)* wise servants dared himself to tell the king not to waste huge money unnecessarily. Instead, a little piece of leather can be used to cover *the(an,a)* king’s foot. The king was surprised, but *he(she,it)* later agreed to his suggestion, to make a shoe for himself.`,
        `A Wolf found great difficulty in getting at *the(a,an)* sheep's owing to the vigilance of the shepherd and his dogs. But one day *it(he,she)* found the skin of a sheep that *had(have,has)* been flayed and thrown aside. so *it(her,him)* put it on over its own pelt and strolled down among the sheep. The Lamb *that(these,this)* belonged to the sheep, whose skin the Wolf *was(is,wear)* wearing, began to follow the Wolf in the Sheep’s clothing. so, leading the Lamb *a(the,an)* little apart, he soon made a meal off *her(hers,it)*, and for some time *he(she,hers)* succeeded in deceiving the sheep, and enjoying hearty meals.`,

        `Once there lived *a(an,the)* grumpy king. *He(she,him)* never used to laugh nor allow anyone in the kingdom to laugh. One day, *a(the,an)* small boy couldn't control *his(him,her)* laughter. Later, scared of the punishment, he thought of *a(an,the)* plan. He wrote a funny story *and(but,yet)* converted it into a drama. Then he went to the palace and asked *the(a,an)* king for permission to enact the dramaThe king let *him(her,his)* do it. Then *the(she,him)* boy started the play. In *the(an,a)* end, he came to the funniest part of the story which made the king laugh. All people present in the court *were(was,is)* amazed. The king then allowed everybody *to(for,with)* laugh. Everyone *then(they,their)* lived happily thereafter.`,

        `Once there *was(were,had)* a Lion in the jungle which used to kill other animals daily for *his(your,their)* meal. All the animals went to *him(her,his)* to tell, that daily one of them would come to him *for(with,to)* his meal. The Lion also agreed and *this(that,they)* started going for many days. One day, it *was(were,has)* Rabbit’s turn. When he was *on(by,in)* his way he saw a well. Now he plans to kill the lion *and(it,will)* save himself. He went to *the(a,an)* lion and told him that, there *is(was,were)* another lion who claims to be more powerful than him.Then the lion asks *the(a,an)* rabbit to take him to that lion. The rabbit takes him *to(for,were)* the well and says he lives here. When the lion looked in the well *he(him,his)* saw his own reflection and jumped in the well and died.`,

        `Once a teacher *had(have,has)* a disciple who used to live in a hermitage. One day, the disciple *was(were,are)* going somewhere. He *had(have,has)* not gone too far but suddenly it started raining cats and dogs. He returned and told *his(her,him)* problems to his teacher. The teacher said to have faith *in(of,so)* God. He will save *him(his,her)* from all problems.*The(this,a)* disciple obeyed and resumed his journey. He kept reciting *the(an,a)* name of god and cleared all the hurdles. Next day, the teacher *had(have,has)* to go on the same route. When he reached *a(an,the)* deep drain, he doubted whether God *would(will,shall)* save him or not. *The(these,those)* teacher drowned. Thus, doubt drowns the teacher and faith saves *the(a,an)* disciple.`,

        `One day a hunter set *a(the,an)* net to catch birds. Placed grains *and(but,yet)* rice over the net. After some time *a(the,an)* flock of pigeons comes by and start eating grains. They *did(do,does)* not notice the net. *They(their,them)* get caught in the net. The pigeons tried *to(of,on)* escape from the net. All their ways to escape ended *in(on,of)* vain. They lost *their(his,her)* hope. Then, their leader asks them to fly together up in *the(a,an)* sky. They did as they *were(are,was)* told and carried the net away. The hunter runs after *them(it,they)* but they flew away to their friend’s mouse hole. Then the mouse cuts the net and freed *the(a,an)* pigeons.`,

        `Once upon a time, beside a lake, *there(here,these)* lived a tortoise and two geese who *were(are,was)* great friends. As the lake *was(is,am)* drying, the geese decided to migrate to*a(the,an)* new place. The tortoise also wanted *to(for,on)* move with them, but *he(they,their)* couldn’t fly. so he pleaded *with(on,as)* the geese to take him with them. After trying really hard to convince *them(they,him)*, finally, the geese agreed. They held *a(the,an)* stick with their beaks and asked the tortoise to hold the stick with *his(their,them)*  mouth, warning him to not open his mouth and let go of the stick. As they flew high, some onlookers thought *that(they,them)* the tortoise was kidnapped and commented that the tortoise *is(was,were)* poor.This angered the tortoise and *he(they,his)* immediately opened his mouth to say something back. As soon as he did*(does,do)*, he fell to the ground and died.`,

        `Once upon *a(an,the)* time, a jackal wandered away from *his(them,they)* jungle and reached a deserted battlefield. He *was(is,were)* very hungry, and so he started looking *for(in,to)* food. He heard *a(an,it)* strange sound. The jackal got scared and decided *to(it,on)* run away, but then he thought, let *him(you,me)* carefully see who is making that sound. As *he(I,you)* looked around, he found *an(a,the)* abandoned drum lying next to a tree, and as *the(an,a)* wind blew, the branches of the tree rubbed against *it(you,her)*, making the sound. He *was(is,were)* relieved and continued to search for food.`,

        `A gang of owls attacked some crows *in(with,yet)* a forest, one night, and killed them all. Because *the(a,an)* crows couldn’t see clearly at night, *they(it,them)* couldn’t fight back. The King of the crows *was(were,are)* so distressed to hear the news, that he went to *his(her,him)* wise old minister for guidance. The minister gave him some advice *and(so,or)* sent him back. The next day, *the(a,an)* crows went to the owl’s cave and put *on(to,of)* a dramatic show. One crow pretended to praise *the(an,a)* owls and the other ones struck him down. Seeing this, *the(a,an)* Owl King thought that *this(these,they)* crow was in favour of the owls. The crow continued to live with the owls, till one morning, *the(an,a)* crow flew away, and with the help of his crow friends, sets fire to the entrance of the owl cave. Since owls *are(was,were)* nocturnal creatures, they were fast asleep, and all of them *were(is,are)* killed!`
      ]
    },
    {
      id: 'fillup-2',
      label: 'Fillup - Collection 2',
      type: 'fillupOptions',
      commonData: {
        title: 'Click on the blanks and pick the correct option.'
      },
      data: [
        `One hot day, an ant was searching *for(with,to)* some water. After walking around for some time, she came *to(from,in)* a spring. To reach the spring, she *had(has,have)* to climb up a blade of grass. While making her way up, she slipped *and(still,yet)* fell into the water. She could *have(has,had)* drowned if a dove up a nearby tree *had(have,has)* not seen her. Seeing that *the(an,a)* ant was in trouble, the dove quickly plucked *off(of,on)* a leaf and dropped *it(these,those)* into the water near the struggling ant. The ant moved towards the leaf and climbed *up(down,to)* there. Soon *it(I,we)* carried her safely to dry ground. Just at that time, a hunter nearby *was(is,are)* throwing out his net towards the dove, hoping to trap it. Guessing what he was about *to(on,in)* do, the ant quickly bit *him(her,his)* on the heel. Feeling *the(a,an)* pain, the hunter dropped his net. The dove *was(were,is)* quick to fly away to safety.`,

        `Once upon a time there lived a group *of(as,on)* mice under a tree peacefully. But once a group of elephants came *that(this,in)* way and destroyed the homes of all the rats. As a result many of *them(they,those)* were crushed to death. Then the king of rats decided *to(for,of)* approach the elephant chief and request *him(his,her)* to guide his herd through another route. The elephant king agreed to this *and(or,yet)* took another route to the water. And so the lives of the rats *were(was,are)* saved. One day a group of elephant-hunters came and trapped the group of elephants *in(on,to)* huge nets. *Then(than,them)* the elephant king suddenly remembered the king of the rats. He summoned one of the elephants of his herd *which(when,what)* had not been trapped, to go and contact the king of rats. *On(to,in)* listening to the elephant, the rat king took his entire group of mice and they cut open the nets which trapped the elephant herd. *So(as,in)* the elephant herd was totally set free.`,

        `One beautiful spring morning, a merchant loaded his donkey *with(to,on)* bags of salt to go to the market *in(with,upon)* order to sell them. The merchant and his donkey *were(are,was)* walking along together. They *had(have,had)* not walked far when they reached a river *on(in,too)* the road. Unfortunately, the donkey slipped and fell *into(on,with)* the river and noticed that the bags of salt loaded on his back became lighter. There was nothing the merchant could *do(did,does)*, except return home where he loaded his donkey *with(within,into)* more bags of salt. *As(so,in)* they reached the slippery riverbank, now deliberately, the donkey fell *into(in,to)* the river and wasted all the bags of salt on its back again. The merchant quickly discovered the donkey’s trick. He then returned home again *but(or,yet)* re-loaded his donkey with bags of sponges. The foolish, tricky donkey again set *on(to,for)* its way. On reaching the river he again fell into the water. But instead *of(on,in)* the load becoming lighter, it became heavier.`,

        `It was a sunny day *and(then,now)* a fox was walking across the fields. Soon he came *to(on,for)* a vineyard. As he came nearer, *he(they,it)* could see some bunches of juicy grapes. The fox looked carefully around him. He *had(have,has)* to make sure that he was safe from the hunters. He decided *to(for,by)* steal some before anyone came along. He jumped upwards but he *could(can,will)* not reach the grapes. He jumped again *as(so,very)* high as he could. He still could not reach them. The grapes were just *too(to,two)* high for him. He was not ready to give up. He backed *off(of,on)*, took some running steps and leapt into the air towards the grapes. Again he failed *to(on,in)* reach them. It was getting dark, and he *was(were,is)* getting angry. His legs hurt *with(at,so)* all that running and jumping. At last he stopped trying. As he walked away, he said to himself that he doesn’t want the grapes because they *are(is,were)* too sour to eat.`,

        `*a (the, an)* great bird named Bharunda lived on the banks of a lake. He had two heads but *a(an,the)* single body. One day,as the bird was wandering *on(of,with)* the bank of the lake, he found a fruit, *which(what,whose)* was as delicious as ambrosia. One of his heads mumbled that it is sure the heavens *have(has,had)* sent it for me. It also exclaimed that it *was(is,were)* lucky. Hearing this, the second head requested *to(for,with)* taste the fruit which the first head was praising *so(to,by)* much. The first head laughed and said they have *the(a,an)* same stomach. It makes no difference whether *who(what,which)* is eating it. It would give it to their beloved. She will *be(am,is)* very happy. Bharunda thus gave the fruit *to(of,with)* his wife. The second head was disappointed at this action of the first head. One day, the second head found a poisonous fruit and told *the(a,an)* first head that it is going to aveng the first head *by(to,for)* eating the poisonous fruit. The second head pleaded not *to(for,on)* eat the fruit because they *have(has,had)* the same body. Ignoring *his(my,him)* warning, the second head ate the poisonous fruit and both of them died.`,

        `A man found *a(the,an)*cocoon of a butterfly. One day a small opening appeared. He sat and watched the butterfly *for(on,in)* several hours as it struggled to force *its(hers,them)* body through that little hole. Then it seemed *to(too,on)* stop making any progress. It appeared as if it *had(has,have)* gotten as far as it could and *it(they,we)* could go no farther. Then the man decided *to(by,with)* help the butterfly. so he took a pair of scissors and snipped *off(of, on)* the remaining bit of the cocoon. The butterfly then emerged easily. But it *had(has,have)* a swollen body and small, shriveled wings. The man continued to watch the butterfly because *he(him,it)* expected that, at any moment, the wings would enlarge and expand to *be(is,been)* able to support the body, which would contract in time. Neither happened. In fact, the butterfly spent *the(an,a)* rest of its life crawling around with a swollen body and shriveled wings. It never was able *to(for,by)* fly. What this man in *his(her,him)* kindness and haste *did(do,does)* not understand that the restricting cocoon and the struggle required *for(in,on)* the butterfly to get through the tiny opening was nature's way of forcing fluid *from(for,form)* the body of the butterfly into its wings so that it would be ready for flight once it achieved its freedom from the cocoon.`,

        `In ancient times, a king *had(have,has)* a boulder placed on a roadway. Then he hid himself and watched to see if anyone *would(will,shall)* remove the huge rock. Some of the king’s wealthiest merchants and courtiers came *by(on,in)* and simply walked around it. Many loudly blamed the king for not keeping the roads clear, but none *did(do,does)* anything about getting the big stone out of *the(a,an)* way. Then a peasant came along carrying a load *of(for,to)* vegetables. On approaching the boulder, the peasant laid down *his(him,he)* burden and tried to move the stone to the side of the road. After much pushing and straining, he finally succeeded. As the peasant picked *up(down,upon)* his load of vegetables, he noticed a purse lying in the road *where(there, when)* the boulder had been. The purse contained many gold coins and a note from the king indicating that the gold *was(were,is)* for the person who removed the boulder from the roadway. The peasant reached home cheerfully.`,

        `A father *had(have,had)* a family of sons who were perpetually quarreling among themselves. When he failed to heal *their(them,they)* disputes by his exhortations, he determined to give them a practical illustration of the evils of disunion. And for this purpose he one day told *them(they, there)* to bring him a bundle of sticks. When they *had(have,has)* done so, he placed the faggot into the hands of each of them *in(to,with)* succession, and ordered them to break it into pieces. They tried with all their strength, and *were(was,is)* not able to do it. He next opened the faggot, took the sticks separately, one by one, and again put them into his sons’ hands, upon *which(what,where)* they broke them easily. He then addressed them *if(of,on)* they are of one mind and unite to assist each other they *will(should,must)* be as this faggot, uninjured by all the attempts of their enemies *but(as,yet)* if they are divided among themselves they can be easily broken as easily as these sticks. The sons then realised that they should be united and they promised *that(this,these)* they would not quarrel.`,

        `One night, three thieves stole a lot of money *from(with,into)* a rich man’s house. They put the money *in(on,of)* a bag and went to the forest. They felt very hungry. So, one of them went *to(on,from)* a nearby village to buy food. The other two remained in the forest to take care *of(on,at)* the bag of money. The thief who went for food *had(has,have)* an evil idea. He ate his food at a hotel. Then he bought food *for(far,so)* his two mates in the forest. He mixed a strong poison *with(up,too)*the food. He thought the other two would eat *this(those, were)* poisoned food and die. Then he *will(would, wouldn't)* get all the money for himself. Meanwhile, the two wicked men in the forest decided to kill *their(them,they)* mate in return. They thought that they would divide the money between the two *of(off,in)* them. All the three wicked men carried out their cruel plans. The thief who wanted all *the(a,an)* money for himself came to the forest with the poisoned food. The two men in the forest hit *him(them,they)* and killed him. Then they ate the poisoned food and died. Thus, these evil people met *with(from,to)* an evil end.`,

        `One hot day, a thirsty crow flew all over the fields looking *for(of,to)* water. For *a(the,an)* long time, she could not find any. She felt very weak, almost giving *up(down,to)* hope. Suddenly, she saw a water jug below her. She flew straight down to see if *there(where,when)* was any water inside. She *could(will, may)* see some water inside the jug. The crow tried to push her head *into(with,by)* the jug. Sadly, she found that the neck of the jug *was(were,is)* too narrow. She tried to push the jug down for the water to flow out. She found *that(this,them)* the jug was too heavy. The crow thought, hard for *a(the,an)* while. Then looking around her, *she(it,him)* saw some pebbles. She suddenly *had(have,has)* a good idea. She started picking up the pebbles one *by(on,in)* one, dropping each into the jug. As more and more pebbles filled the jug, the water level kept rising. Soon it was high enough for the crow to drink. Her plan *had(have,has)* worked!`
      ]
    },
    {
      id: 'fillup',
      label: 'Fillup - Collection 3',
      type: 'fillupOptions',
      commonData: {
        title: 'Click on the blanks and pick the correct option.'
      },
      data: [
        `A milkmaid was on her way to the market to *sell(sold,sales)* some milk from her cow. As she *carried(carries,carry)* the large jug of milk on top of her head, she began to *dream(dreaming,dreamt)* of all the things she could do after selling the milk. She dreamt that, with that money, she will *buy(buying, bought)* a hundred chicks to rear in her backyard. When they are fully *grown(grow,grows)*, she can sell them at a good price at the market. As she *walked(walk,walks)* on, she continued dreaming, then she would buy two young goats and *rear(rearing,rears)* them on the grass close by. When they are fully grown, she can sell them at an even *better(good,worse)*price. Still dreaming, she said to herself, soon, she will be *able(abled,abling)*to buy another cow, and she will have more milk to sell. Then she shall have even more money. With these happy *thoughts(think, thinking)*, she began to skip and jump. Suddenly she tripped and *fell(fall,falls)*. The jug broke and all the milk spilt onto the ground. No more dreaming now, she *sat(sit,sits)* down and cried.`,

        `A selfish fox once *invited(invites, inviting)* a stork to dinner at his home in a hollow tree. That evening, the stork *flew(flt,flies)* to the fox’s home and knocked on the door with her long beak. The fox opened the door and *said(say,says)* please come in and share his food. The stork was invited to *sit(sat,sits)* down at the table. She was very hungry and the food *smelled(smells, smelling)* delicious. The fox served soup in shallow bowls and he *licked(lick,licks)* up all his soup very quickly. However, the stork could not *have(has,had)* any of it as the bowl was too shallow for her long beak. The poor stork just *smiled(smile, smiling)* politely and stayed hungry. The selfish fox asked, why hadn't the stroke *taken(take,takes)* it’s soup. The stork replied that It was very kind of him to invite her for dinner. Crane invited the fox to join her for dinner in her house the next evening.  The next day, when the fox *arrived(arrive, arriving)* at the stork’s home, he saw that they were also having soup for dinner. This time the soup was *served(serve, serving)* in tall jugs. The stork drank the soup easily but the fox could not reach inside the tall jug. This time it *was(is,were)* his turn to go hungry.`,

        `Once upon a time, there was a hungry fox that was *looking(looks,looked)* for something to eat. He was very hungry. No matter how hard he tried, the fox could not *find(finds,found)* food. Finally he *went(go, going)* to the edge of the forest and searched there for food. Suddenly he *caught(catch, catches)* sight of a big tree with a hole in it. Inside the hole was a package. The hungry fox immediately thought that there *might(may,must)*be food in it, and he became very happy. He jumped into the hole and when he *opened(open,opens)* the package, he saw there was a lot of food, bread, meat and fruit in it. An old woodcutter had *placed(place,places)* the food in the tree trunk while he cut down trees in the forest. He was going to *eat(eating,eats)*it for his lunch. The fox happily *began(begin, beginning)* to eat. After the fox had finished eating, he felt thirsty and *decided(decide, decides)* to leave the trunk and drink some water from a nearby spring. However, no matter how hard he *tried(try,tried)*, he could not get out of the hole. the fox had eaten so much food that he *became(become, becoming)* too big to fit through the hole. The fox was very sad and upset. He told himself he *wished(wish, wishing)* that he had thought a little before *jumping(jump,jumped)* into the hole.`,

        `Once upon a time, there lived *(lives,live)* a cloud that grew over a very beautiful country. One day, she saw another much *bigger(big, biggest)* cloud and she felt so much envy, then the cloud *decided(will decide,decides)* that in order to get bigger and grow more, her water would never abandon her, and will never start *raining(rain,rains)* again. Indeed, the cloud grew up, while his country was *getting(get,got)* dried. First, rivers dried up, then people, animals, plants, and finally, the whole country *became(become, becoming)* a desert. The cloud *did(does,do)* not care much, but she also did not *realize(realised,realising)* that by being over a desert there was no place where she could *obtain(obtained, obtains)* new water to keep growing. So slowly, the cloud began to *lose(lost, losing)* size, and was unable to do anything to stop it . The cloud then realized her mistake, and that her greed and selfishness were the cause of her *vanishing(vanish, vanished)*; but just before evaporating, when she was just a sigh of cotton, there *started(start, starting)* blowing a gentle breeze. The cloud was so small and weighed so little that the wind *took(takes, take)* her far away, to a far away beautiful country, where once again she *recovered(recover,recovers)* her original size. Having learned this lesson, our cloud remained *small(smallest, smaller)* and modest, but she became so generous when raining, that her new country became even greener, *giving(gives,gave)* away to all people there the most beautiful rainbow in the world.`,

        `Once upon a time, a hippopotamus *lived(lives,lived)* in a river next to a big and solitary tree. One day, a bird *came(comes, come)* and nested in the tree. The songs and the flight of the bird caused such an envy in the hippo that he couldn't *think(thought,thinks)* of anything else. Every day he would *lament(laments,lamenting)* the fact that he had been born a hippo. This, despite the many times the bird *told(tell,tells)* that the hippo was so lucky to be so big and such a good swimmer. Finally, the hippo *made(make,making)* his mind up that he would come out of the river, climb the tree, *go(goes,gone)* out to perch on a branch, and start singing. However, when he tried to *climb(climbing,climbs)* the tree it was all too clear that the hippo didn't *have(has,had)* wings, nor claws to climb with, and neither could he hop. Realising that he would never manage it, he angrily rammed his whole weight against the tree until it came *crashing(crash, crashed)* to the ground. Then, triumphantly, he stepped onto the leaves of the *fallen(falling,fell)* tree, and began singing. Unfortunately, hippos can't sing either. All that came from his mouth were horrible noises, and when the other animals *heard(hear, hearing)* this they all gathered round to make fun of the hippo standing on the branch of a fallen tree, trying to *sing(singing,sang)* like a bird. He was so embarrassed by this that he *decided(decide, decides)* to never again regret being a hippo. He also felt bad about having knocked the tree over. He used all his strength to raise the tree back up again, *replant(replanted, replanting)* it, and look after it until it has completely recovered.`
      ]
    }
  ]
};
